[project]
name = "auditagent"
version = "0.1.0"
description = "The Document Review Intelligent Agent is an AI-powered assistant based on large language models, designed to help enterprise employees quickly understand document review policies, audit document materials, and improve review efficiency."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
